model_name: "cnn"
batch_size: 8
num_epochs: 1
train_metadata_path: metadata/new_zuzanna/train_metadata.json
validation_metadata_path: metadata/new_zuzanna/val_metadata.json
test_metadata_path: metadata/new_zuzanna/test_metadata.json
synthetic_metadata_path: metadata/synthetic_metadata.json
out_checkpoint_path: model_checkpoints/classifier/classifier.pt
use_synthetic: False
dataset_names: 
  - bcdr
  - inbreast
image_size: 128
classify_binary_healthy: True