birads_min: 2
birads_max: 6
batch_size: 8
num_epochs: 100
train_metadata_path: metadata/classifier_metadata/train_metadata.json
validation_metadata_path: metadata/classifier_metadata/val_metadata.json
test_metadata_path: metadata/classifier_metadata/test_metadata.json
synthetic_metadata_path: metadata/synthetic_metadata.json
train_shuffle_proportion: 0.4
out_checkpoint_path: model_checkpoints/classifier/classifier.pt
validation_shuffle_proportion: 0
classes: is_healthy
use_synthetic: True
dataset_names: 
  - bcdr
  - inbreast
