model_name: "cnn"
batch_size: 8
num_epochs: 1
train_metadata_path: metadata/binary_metadata/train_metadata.json
validation_metadata_path: metadata/binary_metadata/val_metadata.json
test_metadata_path: metadata/binary_metadata/test_metadata.json
synthetic_metadata_path: metadata/synthetic_metadata.json
train_shuffle_proportion: 0.4
validation_shuffle_proportion: 0
classes: is_healthy
use_synthetic: False
dataset_names: 
  - bcdr
  - inbreast
is_trained_on_calcifications: False
image_size: 128
classify_binary_healthy: True