model_name: "swin_transformer"
batch_size: 8
num_epochs: 300
train_metadata_path: metadata/classifier_binary_merged/train_metadata.json
validation_metadata_path: metadata/classifier_binary_merged/val_metadata.json
test_metadata_path: metadata/classifier_binary_merged/test_metadata.json
synthetic_metadata_path: metadata/synthetic_metadata.json
train_shuffle_proportion: 0.
out_checkpoint_path: model_checkpoints/classifier/classifier.pt
validation_shuffle_proportion: 0
classes: is_healthy
use_synthetic: False
dataset_names: 
  - bcdr
  - inbreast
is_trained_on_calcifications: True
image_size: 64
classify_binary_healthy: True
