model_name: "cnn"
batch_size: 8
num_epochs: 30
train_metadata_path: metadata/roo/train_metadata.json
validation_metadata_path: metadata/roo/val_metadata.json
test_metadata_path: metadata/roo/test_metadata.json
synthetic_metadata_path: metadata/roo/synthetic_metadata.json
synthetic_data_dir: combined_synthetic
use_synthetic: True
dataset_names: 
  - bcdr
  - inbreast
image_size: 128
classify_binary_healthy: True