batch_size: 8
num_epochs: 3
train_metadata_path: metadata/binary_metadata/train_metadata.json
validation_metadata_path: metadata/binary_metadata/val_metadata.json
test_metadata_path: metadata/binary_metadata/test_metadata.json
synthetic_metadata_path: metadata/synthetic_metadata.json
train_shuffle_proportion: 0.4
out_checkpoint_path: model_checkpoints/classifier/classifier.pt
validation_shuffle_proportion: 0
classes: is_healthy
use_synthetic: False
dataset_names: 
  - bcdr
  - inbreast
is_trained_on_calcifications: True
image_size: 64
classify_binary_healthy: True