model_name: "swin_transformer"
batch_size: 2
num_epochs: 300
train_metadata_path: setup/classifier_binary_merged/train_metadata.json
# train_metadata_path: /Users/zuzanna/Desktop/eucanimage/mammo_gans/metadata/healthy_inbreast_bcdr_metadata_2.json
validation_metadata_path: setup/classifier_binary_merged/val_metadata.json
# validation_metadata_path: /Users/zuzanna/Desktop/eucanimage/mammo_gans/metadata/healthy_inbreast_bcdr_metadata_2.json
test_metadata_path: setup/classifier_binary_merged/test_metadata.json
synthetic_metadata_path: metadata/synthetic_metadata.json
train_shuffle_proportion: 0.
validation_shuffle_proportion: 0
classes: is_healthy
use_synthetic: False
dataset_names: 
  - bcdr
  - inbreast
is_trained_on_calcifications: True
image_size: 128
classify_binary_healthy: True
