model_name: "cnn"
batch_size: 8
num_epochs: 50
train_metadata_path: metadata/roo/train_metadata.json
validation_metadata_path: metadata/roo/val_metadata.json
test_metadata_path: metadata/roo/test_metadata.json
synthetic_metadata_path: metadata/roo/synthetic_metadata.json
out_checkpoint_path: model_checkpoints/classifier/classifier.pt
use_synthetic: False
dataset_names:
  - inbreast
  - bcdr
image_size: 128
classify_binary_healthy: True