model_name: "cnn"
batch_size: 8
num_epochs: 50
train_metadata_path: metadata/richardosuala/CLF/train_metadata.json
validation_metadata_path: metadata/richardosuala/CLF/val_metadata.json
test_metadata_path: metadata/richardosuala/CLF/test_metadata.json
synthetic_metadata_path: metadata/richardosuala/CLF/synthetic_metadata.json
use_synthetic: False
dataset_names:
  - inbreast
  - bcdr
image_size: 128
classify_binary_healthy: True