model_name: "swin_transformer" #"cnn"
pretrain_classifier: True
are_Ds_alternating_to_update_G: True
batch_size: 16
image_size: 128
use_lsgan_loss: False
switch_loss_each_epoch: False
kernel_size: 6
use_one_sided_label_smoothing: True
conditioned_on: birads
conditional: False
is_condition_binary: True
is_condition_categorical: False
split_birads_fours: False
is_trained_on_masses: True
is_trained_on_calcifications: False
is_trained_on_other_roi_types: False
is_training_data_augmented: True
leakiness: 0.1
num_epochs: 1000
ngpu: 1
dataset_names:
  - bcdr
  - inbreast
