birads_min: 2
birads_max: 6
batch_size: 16
image_size: 64
use_lsgan_loss: False
switch_loss_each_epoch: True
use_discriminator_kernel_size_6: True
leakiness: 0.2
conditional: True
num_epochs: 60
ngpu: 1