birads_min: 2
birads_max: 6
batch_size: 16
image_size: 128
use_lsgan_loss: False
switch_loss_each_epoch: False
use_discriminator_kernel_size_6: True
use_one_sided_label_smoothing: True
split_birads_fours: False
leakiness: 0.2
conditional: False
num_epochs: 60
ngpu: 1