model_name: None #"cnn" # "swin_transformer"
pretrain_classifier: False
are_Ds_alternating_to_update_G: False
start_training_D2_after_epoch: 0
start_backprop_D2_into_G_after_epoch: 0
beta1: 0.5
beta2: 0.9 # This is different to DCGAN's 0.999
ndf: 64
ngf: 64
batch_size: 16
image_size: 128
use_lsgan_loss: False
switch_loss_each_epoch: False
kernel_size: 6
use_one_sided_label_smoothing: True
conditioned_on: None
conditional: False
is_condition_binary: True
is_condition_categorical: False
split_birads_fours: False
is_trained_on_masses: True
is_trained_on_calcifications: False
is_trained_on_other_roi_types: False
is_training_data_augmented: True
leakiness: 0.1
lr_g: 0.0001
lr_d1: 0.0001
lr_d2: 0.0001
added_noise_term: 0.5
beta1: 0.5
nz: 100
weight_decay: 0
num_epochs: 5000
workers: 2
ngpu: 1
dataset_names:
  - bcdr
