from pathlib import Path

INBREAST_ROOT_PATH = Path("/path/to/InBreast/InBreast/")

INBREAST_IMAGE_PATH = INBREAST_ROOT_PATH / "AllDICOMs/"
INBREAST_XML_PATH = INBREAST_ROOT_PATH / "AllXML/"
INBREAST_ROI_PATH = INBREAST_ROOT_PATH / "AllROI/"
INBREAST_CSV_PATH = INBREAST_ROOT_PATH / "INbreast.csv"

