from pathlib import Path

INBREAST_ROOT_PATH = Path("/home/zuzanna/Desktop/gan_aug/InBreast/InBreast/")
INBREAST_IMAGE_PATH = INBREAST_ROOT_PATH / "AllDICOMs/"
INBREAST_XML_PATH = INBREAST_ROOT_PATH / "AllXML/"
INBREAST_ROI_PATH = INBREAST_ROOT_PATH / "AllROI/"
INBREAST_CSV_PATH = INBREAST_ROOT_PATH / "INbreast.csv"
