model_name: "cnn"
batch_size: 12
num_epochs: 100
train_metadata_path: metadata/final_inbreast_metadata/train_metadata_ub.json
# train_metadata_path: /Users/zuzanna/Desktop/eucanimage/mammo_gans/metadata/healthy_inbreast_bcdr_metadata_2.json
validation_metadata_path: metadata/final_inbreast_metadata/val_metadata.json
# validation_metadata_path: /Users/zuzanna/Desktop/eucanimage/mammo_gans/metadata/healthy_inbreast_bcdr_metadata_2.json
test_metadata_path: metadata/final_inbreast_metadata/test_metadata.json
synthetic_metadata_path: metadata/synthetic_metadata.json
no_transforms: False
train_shuffle_proportion: 0.5
out_checkpoint_path: model_checkpoints/classifier/cnn_optimam_bcdr
validation_shuffle_proportion: 0
classes: is_healthy
use_synthetic: True
dataset_names:
  - inbreast
training_sampling_proportion: 1.
is_trained_on_calcifications: False
image_size: 128
classify_binary_healthy: True
synthetic_data_dir: synthetic/exp2exp12
