model_name: "swin_transformer"
batch_size: 12
num_epochs: 100
train_metadata_path: metadata/final_inbreast_metadata/train_metadata.json
# train_metadata_path: /Users/zuzanna/Desktop/eucanimage/mammo_gans/metadata/healthy_inbreast_bcdr_metadata_2.json
validation_metadata_path: metadata/final_inbreast_metadata/val_metadata.json
# validation_metadata_path: /Users/zuzanna/Desktop/eucanimage/mammo_gans/metadata/healthy_inbreast_bcdr_metadata_2.json
test_metadata_path: metadata/final_inbreast_metadata/test_metadata.json
synthetic_metadata_path: metadata/synthetic_metadata.json
no_transforms: False
train_shuffle_proportion: 0.
out_checkpoint_path: model_checkpoints/classifier/swin_transformer
validation_shuffle_proportion: 0
classes: is_healthy
use_synthetic: False
dataset_names:
  - inbreast
training_sampling_proportion: 1.
is_trained_on_calcifications: True
image_size: 128
classify_binary_healthy: True
